# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[test]

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run tests with Tox
        run: |
          source venv/bin/activate
          tox -e py

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run linting with Tox
        run: |
          source venv/bin/activate
          tox -e format
          tox -e lint

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run coverage with Tox
        run: |
          source venv/bin/activate
          tox -e coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml

  type_check:
    needs: setup
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run type checks with Tox
        run: |
          source venv/bin/activate
          tox -e type
