name: Retrieve and Save Data

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC; adjust as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  retrieve_data_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and create virtual environment
      run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[test]

    - name: Run data retrieval script
      run: python retrieve_data.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "ci: Update dataframe_id with latest data"
        git push
      env:
        # Required for GitHub Actions to have permissions to push
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
